### ISSUE TITLE
Switch to typescript

### ISSUE THREAD

**Issue by capital-G** [capital-G/webRTCgui#5]
See https://javascript.plainenglish.io/how-to-convert-node-js-code-from-javascript-to-typescript-8e7d031a8f49

**Comment by jimmywarting** [comment]
[You might not need TypeScript... (syntax)](https://jimmywarting.github.io/you-might-not-need-typescript/)

**Comment by capital-G** [comment]
@jimmywarting thanks for the hint but I switched to typescript now as I really enjoy their namespaces and interfaces and allows me to check if I messed anything up in the communication with the CI. It also provides me some much needed sanity when working within the npm ecosystem :)
